services:
    postgres:
      image: postgres:latest
      container_name: postgres
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      ports:
        - 5432:5432
      networks:
        - internal
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    wallet-api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: wallet-api
      ports:
        - 8080:8080
      networks:
        - internal
      environment:
        DATABASE_URL: ${DATABASE_URL}
      depends_on:
        postgres:
          condition: service_healthy

networks:
  internal: